apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seatrain-base.fullname" . }}-sidekiq
  labels:
{{ include "seatrain-base.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.global.sidekiq.replicaCount }}
  selector:
    matchLabels:
      {{- include "seatrain-base.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: background
  template:
    metadata:
      labels:
        {{- include "seatrain-base.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: background
    spec:
    {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ include "seatrain-base.fullname" . }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - name: sidekiqalive
              containerPort: 7433
          command:
            - bundle
            - exec
            - sidekiq
          args:
            - "-C"
            - "config/sidekiq.yml"
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 7433
          #   initialDelaySeconds: 20
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 7433
          #   initialDelaySeconds: 20 # app specific. Time your sidekiq takes to start processing.
          envFrom:
          - configMapRef:
              name: common-env
          {{if .Values.global.dbConnectionString }}
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-connection-string
                key: db_connection_string
          {{ end }}
          {{if .Values.global.railsMasterKey }}
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: rails-master-key
                key: rails_master_key
          {{ end }}
          resources:
            {{- toYaml .Values.global.resources.sidekiq | nindent 14 }}
      # Default helm
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
