apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-cert
spec:
  secretName: tls-cert

  dnsNames:
  {{- range .Values.global.ingress.hosts }}
    - {{ .host | quote }}
  {{- end }}

  issuerRef:
    name: production-tls-issuer
    kind: ClusterIssuer
    group: cert-manager.io
