apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: production-tls-issuer
spec:
  acme:
    # Email address used for ACME registration
    email: {{ .Values.global.https.certificateEmail }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Name of a secret used to store the ACME account private key
      name: production-tls-issuer
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - http01:
          ingress:
            class: nginx
