apiVersion: v2
name: seatrain-base
description: Subchart with common resources for a standard Rails deployment
type: application
version: 0.1.0
appVersion: 1.0

dependencies:
  - name: redis
    version: 10.2.1
    repository: "@stable"
