global:
  image:
    repository: ""
    tag: latest
    pullPolicy: Always

  imagePullSecrets:
    - name: my-pull-secret
  nameOverride: ""
  fullnameOverride: ""

  rails:
    replicaCount: 1

  sidekiq:
    replicaCount: 1

  # ENV variables declared here will be set for both Rails and Sidekiq pods
  commonEnv: {}

  # Values used to generate secrets at chart install/upgrade.
  # These values need to be injected through shell env/CI secrets,
  # Don't set them here and don't commit to source control.
  dbConnectionString:
  railsMasterKey:

  service:
    type: ClusterIP
    port: 80

  https:
    certificateEmail: ""

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      certmanager.io/cluster-issuer: production-tls-issuer
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - host: example.com
        paths: ["/"]
    tls:
      - secretName: tls-cert
        hosts:
          - examle.com

  resources:
    rails: {}
    sidekiq: {}

  redis:
    cluster:
      enabled: true
      slaveCount: 2
    usePassword: false
    # By default, FLUSH and FLUSHALL are disabled in bitnami/redis chart
    master:
      disableCommands: []

  nodeSelector: {}
  tolerations: []
  affinity: {}
  podSecurityContext: {}
  securityContext: {}
